#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"
WORK="$REPO_ROOT/.wizard"
mkdir -p "$WORK"

TS_CLI="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.local.yml)

# clip FILE — put a file on the clipboard so it can be pasted into a browser.
clip() {
  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy < "$1" && printf '  %s✓%s copied to your clipboard\n' "$GREEN" "$RESET"
  else
    note "copy it from: $1"
  fi
}

banner "hawk-mod — local test setup"

# ──────────────────────────────────────────────────────────────────────────
stage "Scope — what this will and won't record"
say "This works fine against your real workspace. What bounds it is the"
say "ROSTER, not the workspace:"
say ""
say "  ${BOLD}hawk-mod only records a conversation that includes someone"
say "  rostered as a student.${RESET} No student in it, nothing is written."
say ""
say "So for a test, two properties keep it contained:"
step "Only YOU enrol. Enrolling grants hawk-mod your DM history — nobody"
note "    else's DMs are visible until they authorise it themselves."
step "Roster only accounts you control. Anyone you don't put on the roster"
note "    as a student is invisible to it."
say ""
warn "Do NOT roster real students yet."
say "That is the point where this stops being a test and starts recording"
say "minors — which needs the mentor agreement and signed parental consent"
say "in place first, per the plan's §4.3."
say ""
say "You'll need a second account to play the 'student'. A +alias works:"
note "    you+student@gmail.com"
if ! confirm "Understood — only you enrolled, no real students rostered?"; then
  say "Stopping. Nothing has been changed."
  exit 0
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Preflight — Docker"
say "Checking Docker and building the image."
if ! docker info >/dev/null 2>&1; then
  warn "Docker isn't running. Start Docker Desktop, then re-run this script."
  exit 1
fi
docker network inspect edge >/dev/null 2>&1 || docker network create edge >/dev/null
say "Docker network 'edge' ready."
say "Building the image (a minute or two the first time)…"
docker build -t hawk-mod:local . >/dev/null
printf '  %s✓%s image hawk-mod:local built\n' "$GREEN" "$RESET"

# ──────────────────────────────────────────────────────────────────────────
stage "Public URL — Tailscale Funnel"
say "Slack has to reach this machine over public HTTPS, for both event"
say "delivery and the OAuth redirect. Tailscale Funnel gives a stable"
say "hostname with a real certificate."
say ""
# Read Self.DNSName specifically — `status --json` also lists every peer, so a
# first-match grep can hand back a different machine on the tailnet.
FUNNEL_HOST="$("$TS_CLI" status --json 2>/dev/null | python3 -c '
import json, sys
try:
    print(json.load(sys.stdin).get("Self", {}).get("DNSName", "").rstrip("."))
except Exception:
    pass
' 2>/dev/null)"
if [[ -z "$FUNNEL_HOST" ]]; then
  warn "Couldn't read this machine's Tailscale name. Is Tailscale signed in?"
  exit 1
fi
PUBLIC_URL="https://${FUNNEL_HOST}"
say "This machine is ${BOLD}${FUNNEL_HOST}${RESET}"
say ""
warn "Read this before agreeing — Funnel is genuinely public."
say "It exposes ONLY port 3000 of this Mac (nothing else on the machine), but"
say "it exposes it to the whole internet. Do not treat the hostname as a"
say "secret: Tailscale gets a Let's Encrypt cert for it, and every issued cert"
say "is published to public Certificate Transparency logs."
say ""
say "What is actually listening on 3000:"
note "  /slack/events         rejects anything without a valid Slack signature"
note "  /slack/oauth_redirect  rejects callbacks without the signed state param"
note "  /slack/install         redirects to Slack's own consent screen"
note "  /health                returns status + how many mentors are enrolled"
say ""
say "No message content, no database, and no admin surface is served over HTTP."
say "The safety here is that every endpoint is authenticated — not that the"
say "URL is hard to guess."
say ""
warn "Funnel persists across restarts. Turn it off when you're done:"
note "    $TS_CLI funnel --https=443 off"
if ! confirm "Start the Funnel now?"; then
  say "Stopping — hawk-mod can't be tested without a public URL."
  exit 0
fi
if ! "$TS_CLI" funnel --bg 3000 >"$WORK/funnel.log" 2>&1; then
  warn "Funnel didn't start. Its output:"
  sed 's/^/    /' "$WORK/funnel.log"
  say ""
  step "Usually this means HTTPS certs or Funnel need enabling for the tailnet."
  step "Enable HTTPS certificates, then re-run this script:"
  open_url "https://login.tailscale.com/admin/dns"
  step "If the output above printed an approval link, open that too."
  exit 1
fi
printf '  %s✓%s funnel serving %s → localhost:3000\n' "$GREEN" "$RESET" "$PUBLIC_URL"
write_env PUBLIC_URL "$PUBLIC_URL"

# ──────────────────────────────────────────────────────────────────────────
stage "Slack — the app"
say "The manifest goes on WITHOUT event subscriptions first."
note "Slack verifies the events URL the moment you save it, and the container"
note "can't answer that challenge until it has this app's signing secret."
note "Chicken-and-egg — so events get switched on in stage 8 instead."
say ""
sed -e "s#https://hawk-mod.example.org#${PUBLIC_URL}#g" \
    -e '/^settings:/,$d' docs/slack-app-manifest.yaml > "$WORK/manifest-step1.yaml"
printf 'settings:\n  org_deploy_enabled: false\n  socket_mode_enabled: false\n  token_rotation_enabled: false\n' \
  >> "$WORK/manifest-step1.yaml"
clip "$WORK/manifest-step1.yaml"
open_url "https://api.slack.com/apps"
if confirm "Do you already have a Slack app you want to use for hawk-mod?"; then
  warn "Pasting this manifest REPLACES that app's entire configuration —"
  warn "its scopes, redirect URLs, slash commands, the lot."
  say "Only do this to an app that is meant to be hawk-mod. If it's a working"
  say "integration doing something else, answer no next time and make a new one."
  if confirm "Replace that app's configuration?"; then
    step "Open the app → 'App Manifest' in the sidebar."
    step "Select YAML, replace the contents with your clipboard, Save Changes."
    step "If it warns that scopes changed, accept — you'll reinstall in stage 9."
  else
    say "Stopping. Nothing has been changed in Slack."
    exit 0
  fi
else
  step "Click 'Create New App' → 'From a manifest'."
  step "Pick the workspace you're testing in."
  step "Choose YAML, replace the contents with your clipboard, Next → Create."
fi
pause "Press Enter once the app is saved."

# ──────────────────────────────────────────────────────────────────────────
stage "Slack — credentials"
say "From the app's Basic Information page, under 'App Credentials'."
open_url "https://api.slack.com/apps"
step "Open your app → Basic Information → App Credentials."
ask SLACK_CLIENT_ID "Client ID:"
step "Click 'Show' on Client Secret, then copy it."
ask_secret SLACK_CLIENT_SECRET "Client Secret (hidden):"
step "Click 'Show' on Signing Secret, then copy it."
ask_secret SLACK_SIGNING_SECRET "Signing Secret (hidden):"
write_env SLACK_CLIENT_ID "$SLACK_CLIENT_ID"
write_env SLACK_CLIENT_SECRET "$SLACK_CLIENT_SECRET"
write_env SLACK_SIGNING_SECRET "$SLACK_SIGNING_SECRET"
say ""
say "Generating the two secrets hawk-mod makes for itself:"
write_env SLACK_STATE_SECRET "$(openssl rand -hex 32)"
write_env TOKEN_ENCRYPTION_KEY "$(openssl rand -base64 32)"
note "TOKEN_ENCRYPTION_KEY encrypts mentors' tokens at rest. On the real"
note "deployment, keep a copy — losing it means everyone re-authorises."
say ""
say "Message text: 'full' stores the text of monitored DMs; 'metadata' stores"
say "who/when/how-many and no text at all. Every policy violation is detected"
say "either way — content only matters when investigating one."
if confirm "Store message text during this test? (no = metadata only)"; then
  write_env LOG_MODE "full"
else
  write_env LOG_MODE "metadata"
fi
write_env TZ "America/New_York"

# ──────────────────────────────────────────────────────────────────────────
stage "Slack — findings channel"
say "Findings are posted to one private channel. It names students, so on the"
say "real workspace it is screened adults only."
step "In your test workspace, create a PRIVATE channel: #youth-protection"
step "Open it → click the channel name → scroll to the bottom of the About tab."
step "Copy the Channel ID (starts with C)."
ask ALERT_CHANNEL_ID "Channel ID:"
write_env ALERT_CHANNEL_ID "$ALERT_CHANNEL_ID"

# ──────────────────────────────────────────────────────────────────────────
stage "Start the container"
say "Starting hawk-mod with the values collected so far."
"${COMPOSE[@]}" up -d --build >/dev/null
say "Waiting for the health check…"
for _ in $(seq 1 30); do
  [[ "$(docker inspect --format '{{.State.Health.Status}}' hawk-mod 2>/dev/null)" == "healthy" ]] && break
  sleep 2
done
if [[ "$(docker inspect --format '{{.State.Health.Status}}' hawk-mod 2>/dev/null)" != "healthy" ]]; then
  warn "Container isn't healthy. Logs:"
  "${COMPOSE[@]}" logs --tail=30 | sed 's/^/    /'
  exit 1
fi
printf '  %s✓%s container healthy\n' "$GREEN" "$RESET"
say "Checking Slack can reach it through the Funnel…"
if curl -fsS --max-time 15 "${PUBLIC_URL}/health" >"$WORK/health.json" 2>&1; then
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$(cat "$WORK/health.json")"
else
  warn "Couldn't reach ${PUBLIC_URL}/health from the public internet."
  step "Check '$TS_CLI funnel status'. Slack cannot work until this responds."
  exit 1
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Slack — switch on events"
say "Now that the container is live and holds the signing secret, apply the"
say "full manifest. Slack will verify the events URL against it."
sed "s#https://hawk-mod.example.org#${PUBLIC_URL}#g" \
  docs/slack-app-manifest.yaml > "$WORK/manifest-step2.yaml"
clip "$WORK/manifest-step2.yaml"
open_url "https://api.slack.com/apps"
step "Open your app → 'App Manifest' in the sidebar."
step "Replace the whole manifest with your clipboard, then Save Changes."
step "It should say the request URL was verified. If not, check the logs with:"
note "    ${COMPOSE[*]} logs -f"
pause "Press Enter once the manifest saved cleanly."

# ──────────────────────────────────────────────────────────────────────────
stage "Install and enrol yourself"
say "Installing puts the bot in the workspace and enrols you as the first"
say "monitored mentor — the same URL does both."
open_url "${PUBLIC_URL}/slack/install"
step "Click through the authorisation screen. Read the scopes it asks for:"
note "    im:history / mpim:history — this is the DM visibility, on your account."
step "You should land on a page confirming you're enrolled."
pause "Press Enter once you see it."
step "In Slack, open #youth-protection and invite the bot: /invite @hawk-mod"
pause "Press Enter once the bot is in the channel."
curl -fsS "${PUBLIC_URL}/health" 2>/dev/null | sed 's/^/  /' || true

# ──────────────────────────────────────────────────────────────────────────
stage "Seed a test roster"
say "hawk-mod decides everything from the roster: who is a student, who is a"
say "screened adult. Two rows is enough to prove it."
say ""
warn "Use only accounts you control. A real person rostered as a student here"
warn "means their DMs with you start being recorded."
ask MENTOR_EMAIL "Your Slack email (the 'mentor'):"
ask STUDENT_EMAIL "The second account's email (the 'student'):"
TODAY="$(date +%F)"
cat > "$WORK/roster.csv" <<CSV
email,full_name,role,ypp_completed_on,mentor_ready_on,cori_completed_on,active,notes
${MENTOR_EMAIL},Test Mentor,mentor,${TODAY},${TODAY},${TODAY},1,wizard test row
${STUDENT_EMAIL},Test Student,student,,,,1,wizard test row
CSV
cat > "$WORK/consents.csv" <<CSV
email,signed_on,form_version,guardian_name,guardian_email,document_ref,recorded_by
${STUDENT_EMAIL},${TODAY},test,Test Guardian,,,wizard
CSV
"${COMPOSE[@]}" cp "$WORK/roster.csv" hawk-mod:/tmp/roster.csv >/dev/null
"${COMPOSE[@]}" cp "$WORK/consents.csv" hawk-mod:/tmp/consents.csv >/dev/null
"${COMPOSE[@]}" exec -T hawk-mod node dist/src/cli/index.js import-roster /tmp/roster.csv | sed 's/^/  /'
"${COMPOSE[@]}" exec -T hawk-mod node dist/src/cli/index.js import-consents /tmp/consents.csv | sed 's/^/  /'
note "Consent is recorded for the student so the only finding you see is the"
note "DM one — drop that row later to watch 'unconsented_account' fire too."

# ──────────────────────────────────────────────────────────────────────────
stage "Prove it works"
say "The actual test: a 1:1 DM between an adult and a student is prohibited"
say "outright, so hawk-mod should flag it the moment it happens."
step "Make sure the student account is in the workspace (invite + accept)"
note "    (a private browser window is the easy way to hold both sessions)"
step "From YOUR account, send that student account a direct message."
pause "Press Enter once you've sent it."
say ""
say "Findings on record:"
"${COMPOSE[@]}" exec -T hawk-mod node dist/src/cli/index.js findings | sed 's/^/  /' || true
say ""
step "Check #youth-protection — the alert should be there too."
note "Nothing yet? The roster matches on email, so confirm the student's Slack"
note "email matches what you typed, then force a sweep:"
note "    ${COMPOSE[*]} exec hawk-mod node dist/src/cli/index.js backfill"

finish
say "Useful from here:"
note "  logs:        ${COMPOSE[*]} logs -f"
note "  findings:    ${COMPOSE[*]} exec hawk-mod node dist/src/cli/index.js findings"
note "  in Slack:    /hawkmod status"
note "  stop:        ${COMPOSE[*]} down"
note "  close the public tunnel: $TS_CLI funnel --https=443 off"
say ""
warn "Wipe the test data before reusing this machine for anything real:"
note "  ${COMPOSE[*]} down -v"
printf '\n'
